# Generated by Django 5.1.5 on 2025-01-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='county',
        ),
        migrations.AddField(
            model_name='hospital',
            name='counties',
            field=models.ManyToManyField(related_name='hospitals', to='data.county'),
        ),
    ]
